- name: docker build and push
  hosts: local
  become: yes
  connection: ssh
  tasks:
    - name: update apt package cache
      apt:
        update_cache: yes

    - name: Build Docker Image
      command: docker build -t Bank-application .
      args:
        chdir: /var/lib/jenkins/workspace/Bank-application

    - name: log in into Docker Hubs
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: anand010
       password: dckr_pat_1bkVc1v1ydKS9LXC_cMw4834huY

    - name: tag image
      command: docker tag Bank-application:latest anand010/Bank-application:latest

    - name: push image
      command: docker push anand010/Bank-application:latest

    - name: Run Container
      command: docker run -d --name BankApp -p 8081:8080 anand010/Bank-application:latest
